'use strict'
const test = require('brittle')
const fs = require('fs')
const path = require('path')
const os = require('os')
const generateSwift = require('../lib/swift-codegen')

// Minimal fake hrpc object for testing
function makeHrpc(handlers) {
  return { handlers }
}

// Helper: strip whitespace for comparison
function normalize(s) {
  return s.replace(/\s+/g, ' ').trim()
}

test('generates file header and imports', (t) => {
  const hrpc = makeHrpc([])
  const output = generateSwift(hrpc)
  t.ok(output.includes('// This file is autogenerated'), 'has autogen comment')
  t.ok(output.includes('import BareRPC'), 'imports BareRPC')
  t.ok(output.includes('import Schema'), 'imports Schema')
  t.ok(output.includes('public class HRPC'), 'defines HRPC class')
})

test('generates _encode and _decode helpers', (t) => {
  const hrpc = makeHrpc([])
  const output = generateSwift(hrpc)
  t.ok(output.includes('private func _encode'), 'has _encode helper')
  t.ok(output.includes('private func _decode'), 'has _decode helper')
  // RPCError.missingResponse appears in request/response method bodies, not in the helpers themselves.
  // Verify it appears when there is a request/response handler:
  const hrpcWithHandler = makeHrpc([
    {
      id: 0,
      name: '@test/cmd',
      request: { name: '@test/cmd-request', stream: false },
      response: { name: '@test/cmd-response', stream: false }
    }
  ])
  const outputWithHandler = generateSwift(hrpcWithHandler)
  t.ok(
    outputWithHandler.includes('RPCError.missingResponse'),
    'request/response method guards nil response'
  )
})

test('generates request/response command', (t) => {
  const hrpc = makeHrpc([
    {
      id: 0,
      name: '@example/get-user',
      request: { name: '@example/get-user-request', stream: false },
      response: { name: '@example/get-user-response', stream: false }
    }
  ])
  const output = generateSwift(hrpc)

  // Client method
  t.ok(output.includes('public func getUser('), 'generates client method')
  t.ok(
    output.includes('async throws -> GetUserResponse'),
    'returns response type'
  )
  t.ok(
    output.includes('_rpc.request(0,'),
    'uses handler.id=0 for command integer'
  )
  t.ok(output.includes('RPCError.missingResponse'), 'guards nil response')

  // Server registration
  t.ok(
    output.includes('public func onGetUser('),
    'generates server registration'
  )
  t.ok(output.includes('@example/get-user'), 'uses fqn as handler key')

  // Dispatch case
  t.ok(output.includes('case 0:'), 'dispatch case uses handler.id')
  t.ok(output.includes('_decode(getUserRequest,'), 'decodes request args')
  t.ok(
    output.includes('req.reply(_encode(getUserResponse,'),
    'encodes and replies'
  )
})

test('generates send-only command', (t) => {
  const hrpc = makeHrpc([
    {
      id: 5,
      name: '@example/log-event',
      request: {
        name: '@example/log-event-request',
        stream: false,
        send: true
      },
      response: null
    }
  ])
  const output = generateSwift(hrpc)

  // Client method — returns void, not async
  t.ok(
    output.includes('public func logEvent('),
    'generates send-only client method'
  )
  t.ok(output.includes('_rpc.event(5,'), 'uses handler.id=5 and event() method')
  t.absent(output.includes('async throws'), 'send-only is not async throws')

  // Server registration — handler takes no return
  t.ok(
    output.includes('public func onLogEvent('),
    'generates send-only server registration'
  )

  // Dispatch case
  t.ok(output.includes('case 5:'), 'dispatch case uses handler.id=5')
  t.absent(output.includes('req.reply'), 'send-only never calls req.reply')
})

test('throws for streaming command at codegen time', (t) => {
  const hrpc = makeHrpc([
    {
      id: 0,
      name: '@example/stream-data',
      request: { name: '@example/stream-data-request', stream: true },
      response: { name: '@example/stream-data-response', stream: false }
    }
  ])
  t.exception(
    () => generateSwift(hrpc),
    /streaming/i,
    'throws for streaming request'
  )
})

test('throws for streaming response at codegen time', (t) => {
  const hrpc = makeHrpc([
    {
      id: 0,
      name: '@example/stream-results',
      request: { name: '@example/stream-results-request', stream: false },
      response: { name: '@example/stream-results-response', stream: true }
    }
  ])
  t.exception(
    () => generateSwift(hrpc),
    /streaming/i,
    'throws for streaming response'
  )
})

test('multiple handlers generate correct dispatch cases', (t) => {
  const hrpc = makeHrpc([
    {
      id: 0,
      name: '@app/get',
      request: { name: '@app/get-request', stream: false },
      response: { name: '@app/get-response', stream: false }
    },
    {
      id: 1,
      name: '@app/ping',
      request: { name: '@app/ping-request', stream: false, send: true },
      response: null
    }
  ])
  const output = generateSwift(hrpc)
  t.ok(output.includes('case 0:'), 'dispatch has case 0 for get')
  t.ok(output.includes('case 1:'), 'dispatch has case 1 for ping')
  t.ok(output.includes('default:'), 'dispatch has default case')
})

test('uses handler.id not array index', (t) => {
  // handler.id=10 but it is first in the array — must use 10, not 0
  const hrpc = makeHrpc([
    {
      id: 10,
      name: '@app/cmd',
      request: { name: '@app/cmd-request', stream: false },
      response: { name: '@app/cmd-response', stream: false }
    }
  ])
  const output = generateSwift(hrpc)
  t.ok(output.includes('_rpc.request(10,'), 'client uses handler.id=10')
  t.ok(output.includes('case 10:'), 'dispatch uses handler.id=10')
  t.absent(output.includes('_rpc.request(0,'), 'does not use array index 0')
})

test('toDisk writes hrpc.json, HRPC.swift, and Package.swift', (t) => {
  const SwiftHRPC = require('../swift.cjs')

  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'hrpc-swift-test-'))
  const outDir = path.join(tmpDir, 'hrpc')

  const hrpcJson = {
    version: 1,
    schema: [
      {
        id: 0,
        name: '@test/hello',
        request: { name: '@test/hello-request', stream: false },
        response: { name: '@test/hello-response', stream: false },
        version: 1
      }
    ]
  }

  const fakeHrpc = {
    toJSON: () => hrpcJson,
    handlers: hrpcJson.schema
  }

  SwiftHRPC._writeToDisk(fakeHrpc, outDir, {
    schemaPackagePath: '../schema',
    schemaPackageName: 'Schema',
    schemaPackageId: 'schema'
  })

  t.ok(fs.existsSync(path.join(outDir, 'hrpc.json')), 'hrpc.json exists')
  t.ok(
    fs.existsSync(path.join(outDir, 'Sources', 'HRPC.swift')),
    'HRPC.swift exists'
  )
  t.ok(
    fs.existsSync(path.join(outDir, 'Package.swift')),
    'Package.swift exists'
  )

  const swift = fs.readFileSync(
    path.join(outDir, 'Sources', 'HRPC.swift'),
    'utf-8'
  )
  t.ok(swift.includes('public class HRPC'), 'HRPC.swift has class definition')
  t.ok(swift.includes('case 0:'), 'HRPC.swift has dispatch for command 0')

  const pkg = fs.readFileSync(path.join(outDir, 'Package.swift'), 'utf-8')
  t.ok(pkg.includes('name: "HRPC"'), 'Package.swift has HRPC target')
  t.ok(
    pkg.includes('bare-rpc-swift'),
    'Package.swift references bare-rpc-swift'
  )
  t.ok(pkg.includes('../schema'), 'Package.swift uses schemaPackagePath')

  const json = JSON.parse(
    fs.readFileSync(path.join(outDir, 'hrpc.json'), 'utf-8')
  )
  t.is(json.version, 1, 'hrpc.json has version')
  t.ok(Array.isArray(json.schema), 'hrpc.json has schema array')

  fs.rmSync(tmpDir, { recursive: true })
})
